### ISSUE TITLE
Add thinking/success/failure reactions

### ISSUE THREAD

**Issue by EpsilonPrime** [andersfylling/disgord#222]
Many bots have the capability to react to a message to show that it's performing a long running action.  It would be useful to add this to the framework.

Code typically looks like:

```go
const (
        thinking = "🤔"
        failure  = "👎"
        success  = "👌"
)

func CallDoSomething(ctx *disgordrouter.Context) {
	ctx.Ses.CreateReaction(ctx.Msg.ChannelID, ctx.Msg.ID, thinking)
	defer func() {
		ctx.Ses.DeleteOwnReaction(ctx.Msg.ChannelID, ctx.Msg.ID, thinking)
	}()
	message, err := logic.DoSomething(ctx.Args[1])
	if err != nil {
		ctx.Reply(fmt.Sprintf("failed: %v", err))
		ctx.Ses.CreateReaction(ctx.Msg.ChannelID, ctx.Msg.ID, failure)
		return
	}
	if _, err = ctx.ReplyEmbed(message); err != nil {
		ctx.Reply(fmt.Sprintf("failed: %v", err))
		ctx.Ses.CreateReaction(ctx.Msg.ChannelID, ctx.Msg.ID, failure)
		return
	}
	ctx.Ses.CreateReaction(ctx.Msg.ChannelID, ctx.Msg.ID, success)
	return
}
```

It'd be nice to include this all in one place.  Bonus points for making the icons configurable.

**Comment by ikkerens** [comment]
I'm a bit puzzled on what exactly you are hoping to achieve here.

Do you want us to add constants for commonly-used emojis? Because while that could work, I personally am of opinion this is just **too** trivial to add to a library, seeing as the "end user" (aka the developer) literally only has to add 1 line to add the constant to their own code.

I think I'd sooner recommend use something like: https://github.com/tmdvs/Go-Emoji-Utils

**Comment by EpsilonPrime** [comment]
I think the code is going to end up looking something like this:

```
func WithProgressReactions(cmd func(s disgord.Session, m *disgord.MessageCreate) error) func(s discord.Session, m *disgord.MessageCreate) {
        return func(s disgord.Session, m *disgord.MessageCreate) {
                ctx.Ses.CreateReaction(ctx.Msg.ChannelID, ctx.Msg.ID, thinking)
                defer func() {
                        ctx.Ses.DeleteOwnReaction(ctx.Msg.ChannelID, ctx.Msg.ID, thinking)
                }()
                if err := cmd(s, m); err != nil {
                        ctx.Ses.CreateReaction(ctx.Msg.ChannelID, ctx.Msg.ID, failure)
                        return
                }
                ctx.Ses.CreateReaction(ctx.Msg.ChannelID, ctx.Msg.ID, success)
        }
}
```

To use, one would insert this around their function that they would normally pass to client.On (and modify their function to return an error).  Here I've used hard-coded constants but given that others have used different icons for their progress reactions it should be made configurable (or an incontrovertibly perfect set if reaction icons should be chosen).

**Comment by andersfylling** [comment]
_edited you comment to use the go language identifier in your markup_

So for a time I've wanted to add a progress bar to messages, through update. This isn't directly discord related, so it would reside in the std pkg.

This is a simplification of that. But still within the same category, so this would be in the std-pkg as well.

I think the function wrap would work nicely as it's plug and play. But I think it should also take a config struct for the emoji types. So is thinking/success/failure some sort of software pattern, since it's named thinking instead of working - link(s)?

**Comment by EpsilonPrime** [comment]
I named it that based on the three icons I ended up choosing.  The pattern is one that I noticed a number of bots with long running computations using.  It's appropriate for stuff that might take a minute but it seems like a different mechanism is needed for something that might take 5 minutes or more.  One approach for really long computations that I've seen is a response that provides information about where you are in queue.

**Comment by EpsilonPrime** [comment]
Seems to work.  Fixed up an issue with it reacting to its own messages by adding a bot ignore.  Still need to make the icons customizable, add a doc page, and tests.

**Comment by andersfylling** [comment]
I'm about to release rc8, and shortly v0.12 after that. If you want this feature by the v0.12 release I suggest making a PR so it can be reviewed in time :)

**Comment by andersfylling** [comment]
Closed due to age
