### ISSUE TITLE
Check if user has permission to send a message

### ISSUE THREAD

**Issue by crackhd** [andersfylling/disgord#254]
How do you check permissions of the bot in a specific channel of a specific guild?

1. Which bitwise operation is applied to permission masks to calculate the result?
2. What is the order of mixing permission masks 
3. What is the order of roles (if a user has multiple roles, how to calculate his SendMessage permission in a channel) in the calculation of yes/no permission?

I believe this should be in readme.

**Comment by andersfylling** [comment]
About what I'd want:
To me it would feel intuitive to get DisGord to a state where methods can return a disgord.MissingPermissionErr and do permission checks locally before doing the REST requests (ofc with time aware permission cache). Addition methods for getting the permission mask for a channel is also something I'd like.

Regarding `I believe this should be in readme.`
This is mostly just a wrapper for the Discord API, so currently you need a general awareness of how Discord "just works". Which can be difficult unless you already have the knowledge. I even keep forgetting at times, which really frustrates me - another reason I like making features function behind the scenes.

The readme should just be a narrative for the lib. I don't mind putting specifics like this in the docs/examples folder, as the README can quickly be overwhelming with all the complexities of Discord.


I haven't played around with permission masks yet, so I can't say for certain how ordering of roles affects it - tho I assume they are simply merged through a bitwise OR.

Right now my understanding of how it all works, is to do something like the following:
 - Get the member instance for your bot
 - Get all the Roles for that member instance
 - Fetch the channel object
 - Check if your bot is denied from sending messages by looking at permission overwrites
 - Check if there is a permission overwrite for your user id, as that might simply state that you can send a message.
 - Otherwise start to merge each role permission into a permission buffer, using the bitwise OR operand.
 -- Before you merge a role permission into the buffer, see if there is a permission overwrite for that role - as the overwrite will have priority over the roles permission.

You can also do that merge loop until you either find a permission that allows you to send or deny you from sending.

[permission overwrites](https://discordapp.com/developers/docs/resources/channel#overwrite-object)
[role object](https://discordapp.com/developers/docs/topics/permissions#role-object)


`1. Which bitwise operation is applied to permission masks to calculate the result?`
Basic bit masks, each bit position represents a permission. So AND to verify if a permission bit is set, and OR to merge multiple permission masks together. 0 at any given position states that the permission is not enabled.
```go
permissions := disgord.PermissionReadMessages | disgord.PermissionSendMessages
fmt.Println(permissions & disgord.PermissionSendTTSMessages > 0) // false
fmt.Println(permissions & disgord.PermissionSendMessages > 0) // true
```



`2. What is the order of mixing permission masks`
Order? bit masks can simply be merged to show the true permission mask (I think? I'm lacking experience here).

When it comes to general uncertainty around Discord behaviour, I usually go to the [Discord API server](https://discordapp.com/invite/HBTHbme) and ask in their #api channel.

If you already know how to do this, and are curious about how to fetch this info from DisGord, I'm sorry to say there currently are no helpers for this - yet. And you have to fetch it with idiomatic design, go into each struct/object and do all the manual labor.

Feel free to reply with more questions.

**Comment by crackhd** [comment]
The following is a code converted from Discord.js to Go for Disgord 
from https://discordapp.com/developers/docs/topics/permissions#permission-overwrites

[Gist](https://gist.github.com/crackhd/85e43e845be59f2afa9d280caf0d4044)

But it does not work. 

self, _ := client.GetCurrentUser(...)
member, _ := client.GetMember(..., guild, self.ID)

pc := Permissions{Client: client}

channel, err := client.GetChannel(....)
p := pc.Compute(member, channel)

if p&c == c {
    // always happens
}

**Comment by andersfylling** [comment]
And you have setup an environment where the bot is denied writing a message?

**Comment by crackhd** [comment]
Yes, i just see it gives true

**Comment by andersfylling** [comment]
I'm a bit too occupied to debug that code right now. But I will get back to this once my exams are finished.

**Comment by crackhd** [comment]
All right, i will ping back if will be able to debug it myself

**Comment by crackhd** [comment]
Good news I've fixed the bug, code works, on my tests. I will be using this little helper class, but you may add this or alternative to your library or close the issue.

**Comment by andersfylling** [comment]
What was the bug?

**Comment by crackhd** [comment]
You could look at the diff, idk

**Comment by andersfylling** [comment]
Looks like it was just a matter of merging bot specific permission and not from ever guild role. I'm glad it was easy to resolve.
