### ISSUE TITLE
Create a basic command data structure

### ISSUE THREAD

**Issue by andersfylling** [andersfylling/disgord#280]
The command name (the trigger), description, and callback

**Comment by Dextication** [comment]
For this to be done, first the structure of the command handler must be decided. Will we be using a linear-time solution O(n):
1. Length (in words, highest to lowest) sorted slice? It must be sorted to allow the handler to always first match the longest command (I.e. deepest sub command). Sorting will also help with performance by allowing binary searching.
```
[
*Command,
*Command, 
*Command....]
```
And a command struct like 
```
type Command struct {
    Name string
    Aliases []string
    Args []string // [“int”, “string”, “User|Role”, ...]
    ...
}
```

2. Or a prefix tree:

```
                   root
     command1             command2
cmd1.1    cmd1.2.     cmd2.1.   cmd2.2
```
With a command structure like
```
type Command struct {
    Name string
    // Aliases []string
    Args []string
    Children []*Command
    ...
} 
```

This can be greedily transversed from the root node to the final command in practically logarithmic time.
NB! All commands and sub commands must have their names stored as command + “ “ so `hello` isn’t confused with `helloworld`

3. Hashmap
Hashmaps allow for O(1) access times, so it’d be easy to find the correct command data structure. Resulting in a O(c) where c is the command length in words (including args) because we have to start at the end and slowly decrease the length until a matching command is found. 

Considering the bounds are 0 < c < 1001, this solution is viable, although it is slower than O(n) [amount of commands] in some cases. The main issue is hashing clashes.
e.g.
```
Hash map of {
    “moderation”: *Command, // 1
    “mod”: *Command, // same pointer as 1 (aliases)
    “mod add”: *Command
} ```

And a command struct like
```
type Command struct {
    Name string
    // Aliases []string
    Args []string
   ...
} 
```

**Comment by andersfylling** [comment]
I don't see an advantage of using BST over hashmap in this case. Especially since unordered data is completely okay.

So a `map[string]*Cmd` seems like the fastest to implement. If we worry about memory usage, we can later upgrade it to a rune tree, where each layer represents the next rune (character) of the command title. Then we iterate over the message content once, and figure out if it's a command. This should even be faster and more memory efficient than a hash map as you don't need to initially extract the command name and then hash it and then check the map. 

But I would consider that as a later upgrade, if needed/request. Or if someone just wants a fun project.

**Comment by andersfylling** [comment]
Regarding sub commands, I'm not sure how to deal with this. Currently the first version will just not support it. At least not in an intuitive or "native" way.

But I guess if we support spaces in the rune tree, that would automatically support sub commands as well.

**Comment by Dextication** [comment]
It’s totally possible to support sub commands with a map[string] *Cmd implementation. If when a command is received, we do the following:
Say the command is “hello world @Someone#2020”
Check the map for a command “hello world @someone#2020” => doesn’t exist
Check map for a command “hello world” => does exist! Execute!

If the command is “hello earth”
Check the map for a command “hello earth” => doesn’t exist
Check the map for a command “hello” => exists! Execute!

**Comment by sachinbhutani** [comment]
I am not too experienced with go. 
but cant we use some existing routing library ? where each command is a route ? 
router should allow subcommands and commands with arguments too 
first string become the route and everything else becomes parameters ?
