### ISSUE TITLE
Disgord sending incorrect intents

### ISSUE THREAD

**Issue by iComputeDaily** [andersfylling/disgord#360]
**Describe the bug**
When using the `disgord.New()` function with the correct intents set in the bitmask disgord sends the wrong intents to the server.

**Expected behavior**
When oring the intent constants set [here](https://pkg.go.dev/github.com/andersfylling/disgord@v0.23.2/internal/gateway#Intent) together and placing the value in the `Intents` section of the config struct the ored intents should be sent when connecting to the discord gateway.

**Error messages**
Relevant code:
```
client := disgord.New(disgord.Config {
    Intents: 0,
})
```

Log messages:
```
DEBU[0000] shard 0 intents: { Guilds | GuildMembers | GuildBans | GuildEmojis | GuildIntegrations | GuildWebhooks | GuildInvites | GuildVoiceStates | GuildPresences | GuildMessages | GuildMessageReactions | GuildMessageTyping }
...
ERRO[0000] [ws-e,s:13,shard:0]you sent a disallowed intent for a Gateway Intent. You may have tried to specify an intent that you have not enabled or are not whitelisted for.
```

**Desktop (please complete the following information):**
 - Golang version: v1.15
 - Using Go modules? yes
 - Disgord version? v0.23.2
 - Connected to the gateway before using REST methods? yes

**Additional context**
It appears that the intents shown in the log are always sent no mater the value of the `Intents` field, but that the last 3 bits for controlling dm capabilities are honored.

**Comment by andersfylling** [comment]
This is technically not a bug, just how disgord works. Disgord derives intents based on the events you want (via the RejectEvents) option. But I agree it's confusing and maybe not even documented/poorly documented.

So this needs an improvement. 

To use it right now, as mentioned on Discord, you use the RejectEvents and then only specify DM intents that you require.

**Comment by andersfylling** [comment]
Please let me know if there are further issues

**Comment by lrstanley** [comment]
Feel like this should be re-opened and used to track the eventual work that I suspect will occur to re-implement this. Unless I'm missing something?

The way this works currently has some serious issues:

- There should never be a "assume all permissions unless rejected" or even a default set of permissions. This seems like a no-brainer for access control related code.
- If a default set of permissions is expected for normal function, these should be provided by Discord itself, not derived from an arbitrary list in a library.
- If a default set of permissions is needed for a library to function (e.g. state tracking and similar), you should add a `disgord.IntentsRequired` or similar, that more obviously identifies the events that are required.
- Assuming permissions that can get automatically added, exposes library users to unwanted auditing concerns, where we may not have realized we were collecting this information, and telling users "we don't capture these things, or require these permissions" when that may randomly change in library updates.
- If Discord eventually adds another intent that requires addl. approval (similar to presence, member list, etc) and this library ends up depending on it, this will also cause the library to effectively break for those implementations.

Given the following Discord API specification:
> If you do not specify a certain intent, you will not receive any of the gateway events that are batched into that group.

This library doesn't adhere. Not only is it not obvious, one runs into weird errors, that aren't due to author code, but due to the libraries magic behind the scenes.

Also, upon trying to get past this issue myself, I'm not sure if I'm doing it correctly, but am I correctly rejecting events? Is there no way to do higher level rejections? Like "IntentGuildMessages`, but... in event form that I can actually reject? Otherwise I seem to have to specify each individual event...:

```go
		RejectEvents: []string{
			disgord.EvtTypingStart,
			disgord.EvtPresenceUpdate,
			disgord.EvtGuildMemberAdd,
			disgord.EvtGuildMemberUpdate,
			disgord.EvtGuildMemberRemove,
			disgord.EvtGuildBanAdd,
			disgord.EvtGuildBanRemove,
			disgord.EvtGuildEmojisUpdate,
			disgord.EvtGuildIntegrationsUpdate,
			disgord.EvtWebhooksUpdate,
			disgord.EvtInviteCreate,
			disgord.EvtInviteDelete,
			disgord.EvtMessageCreate,
			disgord.EvtMessageDelete,
			disgord.EvtMessageDeleteBulk,
			disgord.EvtMessageReactionAdd,
			disgord.EvtMessageReactionRemove,
			disgord.EvtMessageReactionRemoveAll,
			disgord.EvtMessageReactionRemoveEmoji,
			disgord.EvtMessageUpdate,
		},
```

Thoughts?

**Comment by andersfylling** [comment]
```
The way this works currently has some serious issues:
```
To all of those, I agree.

```
one runs into weird errors
```
Such as?

## Regarding intents, guild subscription, and future discord plans 
I don't agree with them, and I don't want to introduce a breaking API until Discord makes more sense. The first iteration where discord tried to optimize away packets was "guild subscription", which had some bugs and removed some events such as presence update. Then they upgraded to intents, which gave us way more and is a fantastic improvement over guild subscription. But I still don't understand intents, they say they are designed by use cases which doesn't seem to be the case, and I wonder why can't we just send the events we want explicitly? Given that the events are absolutes, they don't have any subset values (ignoring DM), it's easier to just design the API around them. And do any such optimization within the library itself.

When it comes to default values for events, in the config, I absolutely agree with you. There shouldn't be any default values. And this is where disgord is going, once this project is complete: https://github.com/andersfylling/discordgateway

In that project, you'll notice that since (some) events are a subset of intents, so you can essentially do something such as:
`intent.GuildMessages.EventFlags()`. https://github.com/andersfylling/discordgateway#intents

It's still being designed, so the README is somewhat outdated / prone to changes.

```
Also, upon trying to get past this issue myself, I'm not sure if I'm doing it correctly, but am I correctly rejecting events? Is there no way to do higher level rejections? Like "IntentGuildMessages`, but... in event form that I can actually reject? Otherwise I seem to have to specify each individual event...:
```
Nope. The closest helper you can get here is `disgord.AllEventsExcept(..)`.

**Comment by andersfylling** [comment]
The gateway project is only missing a refactoring and a shard manager to be up and running: https://github.com/andersfylling/discordgateway
