### ISSUE TITLE
Add example to change channel name

### ISSUE THREAD

**Issue by nuliknol** [andersfylling/disgord#444]
Could you please add an example of how to change channel name? 
It seems that you need to do it through the `Cache`, but there is no way to get `BasicCache` object from the `Client`.

Thanks in advance.

**Comment by andersfylling** [comment]
does `Client.Channel(..).Update().Name("new-name").Execute()` do what you're looking for?

The cache is only updated by the incoming gateway events. This way the cache will only reflect what discord has told us the correct state, instead of being manipulated by a user which can quickly cause bugs and sync issues.

**Comment by nuliknol** [comment]
@andersfylling  are you sure `ChannelQueryBuilder` has `Update()` method?
this is the error I am getting on compilation:

        client.clientQueryBuilder.Channel(ChannelID).Update undefined (type disgord.ChannelQueryBuilder has no field or method Update)

**Comment by nuliknol** [comment]
ohh, it is:

     client.Channel(ChannelID).UpdateBuilder().SetName("mint:111").Execute()

thanks a lot!!!
@andersfylling
