### ISSUE TITLE
Create a comparison chart between DisGord and DiscordGo

### ISSUE THREAD

**Issue by andersfylling** [andersfylling/disgord#90]
What benchmarks can be done, that aren't missleading?
memory usage, cpu usage, etc.

Show how they differ in development, etc.
Try to auto generate as much about the report as possible.

**Comment by Dextication** [comment]
This chart should probably be benchmarked on multiple bot sizes. This can simulated by taking one large bot and running the benchmarks on 1/50, 2/50, 5/50, 10/50, etc. shards. 

The main difficulty will be finding a bot which is large enough for this to be effective, and convince them to run the program. The owners will likely be skeptical of feeding their token to an unknown program. Are there any plans for overcoming this?

I may have a source who is open to doing this.

Here's an example of a chart. Please note that the data is completely random. What do you think? Too many shard categories? Do you think line graphs are better here?
![image](https://user-images.githubusercontent.com/33129361/76943091-795c4880-6907-11ea-88a4-8bbf030bfdc2.png)

I included latency in the example, but I'm not sure whether that's really necessary, since it'll mostly be random while testing, and not really affected by the library.

I think we need to highlight the biggest difference in the libraries:
- discordgo is much more low-level, meaning that it's more customizable but at the expense of developer comfort
- disgord is much more dev-friendly, and it handles sharding on your behalf.

**Comment by andersfylling** [comment]
Nice effort, I like it.

So main differences:
 - discordgo allows self botting, disgord do not.
 - discordgo is not "low-level" but rather idiomatic. However, that becomes an issue when you're dealing with updating information to their zero-values. Last time I checked you can not do that in discordgo. In Disgord you can, that's why you see the builder pattern for update endpoints. I would argue that there has to be a ugly way around it, simply because the discord API isn't the cleanest.
 - the cache is very different. Currently in disgord it's internal, and read only. Allowing for a better chance of correctness of the discord data. I've also heard from someone that disgord had a more accurate caching by default. Which is something to look into for a benchmark.
 - disgord does do sharding for you and you can even do sharding for multiple instances, but it becomes extremely tricky in disgord as of the current version. Hopefully this will be improved upon, somehow.

about the benchmark code, it needs to open sourced and easy to reproduce. Seeing how each lib scale with N shards, would be really cool. Setting up simple benchmarks from the moment a message_create comes into the lib to the point a handler is triggered would also be interesting.

Regarding visual representation. What you have there is nice for a quick summary, but I think using a plot with error bars would make it intuitive to read.

example of plot with error bars (random source on google images[1]):
![image](https://user-images.githubusercontent.com/7851860/77017568-1f956600-697b-11ea-91b9-94511b7e80a4.png)

Issues with disgord as of right now:
 - Voice isn't reconnecting #273 
 - Disgord uses more cpu resources than needed due to the abstracted leaky bucket pattern in the REST API manager (rate limiting) #232 

But yes, having this as a reproducible code base would be really cool. Could also be extended to compare other frameworks. The biggest issue is that some of these tests might require changes to the libs directly to properly extract the info. But hopefully this can be avoided.



1. https://ncss-wpengine.netdna-ssl.com/wp-content/themes/ncss/pdf/Procedures/NCSS/Scatter_Plots_with_Error_Bars.pdf

**Comment by andersfylling** [comment]
I know I want to add a build tag or something for metrics: https://github.com/andersfylling/disgord/issues/136

As I really think it's a good addition, not just to compare against other libs but also for figuring out what to improve on.

**Comment by andersfylling** [comment]
I'm going to close this as disgord keeps changing, and it's honestly not completely clear how disgord will turn out..

I think it's still a nice thing to have, but it just adds technical debt for now. I'll re-open this at a later date.
