### ISSUE TITLE
Simplify updating individual cache settings

### ISSUE THREAD

**Issue by ikkerens** [andersfylling/disgord#95]
Right now in order for someone to update a single cache setting they have to delve into Disgords source to find and copy the default values;
```go
session := disgord.NewSessionMustCompile(&disgord.Config{
	// ...
	CacheConfig: &disgord.CacheConfig{
		Immutable: true,

		UserCacheAlgorithm: disgord.CacheAlgLRU,
		UserCacheLimitMiB:  500,

		VoiceStateCacheAlgorithm: disgord.CacheAlgLRU,

		ChannelCacheAlgorithm: disgord.CacheAlgLFU,
	},
})
```

Effectively negating all default values given by the library. While this is bothersome, there is also the inherent problem of library updates that might change the default values without them being reflected in bots that have already copied over the CacheConfig.

There are a few ways we could look at this, we could implement a `NewDefaultCacheConf` func that makes the default values, or we should look into iterating over all default keys and considering if they've been overwritten by the end developer, instead of simply nil-checking the entire struct.

**Comment by andersfylling** [comment]
See the Go Doc for changes. Essentially every *CacheAlgorithm field is automatically set to default values if not set. And a disgord.DefaultCacheConfig() function now exists.

Note that the total number of users is increased and that Immutable and *CacheLimitMiB is deprecated.

Previously, if you wanted to change one specific field, as Ikkerens mentioned, you would have to specify every field. Now you can specify one field like below (the rest gets the LFU acche strategy and has no maximum entries/limit by default):
```go
session := disgord.NewSessionMustCompile(&disgord.Config{
	// ...
	CacheConfig: &disgord.CacheConfig{
		UserCacheAlgorithm: disgord.CacheAlgLFU,
	},
})
```

However, we can not know whether or not you specified primitive types. Because of this, `disgord.DefaultCacheConfig` was introduced:
```go
conf := &disgord.Config{
	// ...
	CacheConfig: disgord.DefaultCacheConfig(),
}
conf.CacheConfig.UserCacheMaxEntries = 0
session := disgord.NewSessionMustCompile(conf)
```
This allows you to keep all the other default values, compared to creating the CacheConfig struct where only cache algs are defaulted if missing. 

To allow DisGord to keep tweaking the cache configuration on updates (breaking, or minor before v1) you should use the `disgord.DefaultCacheConfig()`. If you want complete control over your configuration, please create the CacheConfig struct yourself.
